- name: add ansible-pull cron job
  cron:
    name: ansible auto-provision
    user: ansible
    minute: "*/5"
    job: sudo ansible-pull -o -U https://github.com/iamsyl/serversetup.git

- name: delete old ansible logs
  cron:
    name: remove ansible logs every 2mins
    user: ansible
    minute: "*/2"
    job:  sudo find /var/log/ansible.log -type f -mmin +5 -exec rm {} +

