#- name: Sync time with AD server
#  shell: systemctl stop ntpd ; ntpdate {{ ad_server_ip }} && systemctl start ntpd
#  register: timesync_result
#  changed_when: false
#  ignore_errors: true
 
- name: Check domain join status
  shell: id {{ad_join_user}}
  register: ad_status
  changed_when: false
  ignore_errors: true

- name: Report AD status
  debug:
    msg: "ad_status is {{ ad_status.rc }}"

- name: Join domain {{ ad_domain }}
  expect:
    command: "realm join  {{ ad_server_ip }} --user={{ ad_join_user }}"
    responses:
      Password for *: "{{ ad_join_pass }}"
  when: ad_status.rc !=0

- name: Allow domain user login without FQDN
  lineinfile:
    backup: yes
    state: present
    dest: /etc/sssd/sssd.conf
    regexp: '^{{ item.search }}'
    line: '{{ item.replace }}'
  with_items:
    - { search: 'use_fully_qualified_names', replace: 'use_fully_qualified_names = False' }
    - { search: 'fallback_homedir', replace: 'fallback_homedir = /home/%u'}
    - { search: 'access_provider', replace: 'access_provider = simple'}
  notify: restart sssd
  when: ad_status.rc !=0

- name: Updating sudoers for domain admin users
  lineinfile: 
     path: /etc/sudoer/domainadmin
     state: present
     regexp: '^%domain\\ admins'
     line: '%domain\ admins ALL=(ALL:ALL) ALL'
     validate: 'visudo -cf %s'
