- name: install packages
  package: 
    name: 
      - wget
      - curl
      - net-tools
      - lsof
      - bash-completion
      - sssd
      - sssd-tools
      - realmd
      - oddjob
      - oddjob-mkhomedir
      - adcli
      - libnss-sss
      - libpam-sss
      - samba-common
      - samba-common-tools
      - samba-common-bin
      - krb5-workstation
      - openldap-clients
      - python3-policycoreutils
  ignore_errors: yes
