- name: install packages
  package: 
    name: 
      - wget
      - curl
      - net-tools
      - lsof
      - bash-completion
      - sssd
      - realmd
      - oddjob
      - oddjob-mkhomdir
      - adcli
      - samba-common
      - samba-common-tools
      - krb5-workstation
      - openldap-clients
      - policycoreutils-python
