- name: add ansible user
  user:
    name: ansible
    system: yes

- name: setup sudo for ansible user
  copy:
    src: files/sudoer_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: install ansible user SSH public key
  authorized_key: 
    user: ansible
    state: present
    key: "{{ lookup('file', 'id_ed25519.pub') }}"
